### ISSUE TITLE
Currently selected item in dialogs not visible

### ISSUE THREAD

**Issue by derwok** [Slowbad/obsidian-solarized#1]
Thanx for this nice theme. Will use the LIGHT theme.
But one minor issue (only tested with light theme): With the current background colors all dialogs that allow line selection do not work. For Example: Global Find (Ctrl+Shift+F); Quick Switch (Ctrl+O) and insertion of Tags or Links.
So when you want to select an item via cursor up/down you don't know what youll get on ENTER.

I made following fix in the light theme:
``` 
    --background-secondary: var(--base2);
    --background-secondary-alt: var(--base3);
``` 
Before:
![2020-05-29_00-20](https://user-images.githubusercontent.com/4393698/83200618-06abec80-a144-11ea-98dd-a7f0b7328462.png)

After:
![2020-05-29_00-28](https://user-images.githubusercontent.com/4393698/83200633-0b70a080-a144-11ea-9472-52edd23403fb.png)

**Comment by Slowbad** [comment]
Thanks. I'll make this change tonight.
