### ISSUE TITLE
Dark theme frontmatter tags unreadable in preview mode

### ISSUE THREAD

**Issue by daneah** [Slowbad/obsidian-solarized#13]
When using the dark theme and viewing a file in preview mode, any frontmatter tags it has are fairly unreadable.

<img width="721" alt="Screen Shot 2021-07-05 at 22 08 48" src="https://user-images.githubusercontent.com/1808306/124531982-9ad39300-dddd-11eb-84ce-04b3a56291b6.png">

Changing `a.color` from `var(--background-primary)` to `var(--text-normal)` fixes this for me locally, but I wasn't sure if that might have any wider impacts because the CSS rule has [a few additional selectors and properties involved](https://github.com/Slowbad/obsidian-solarized/blob/master/obsidian.css#L169-L179).

**Comment by harmtemolder** [comment]
@Barrel-Titor fixed this in #15
