### ISSUE TITLE
Window title barely visible with solarized dark

### ISSUE THREAD

**Issue by memeplex** [Slowbad/obsidian-solarized#16]
Default obsidian dark theme:

![image](https://user-images.githubusercontent.com/2845433/139498610-de0c271d-babf-4220-8a46-43f6a7e8a888.png)

Solarized dark theme:

![image](https://user-images.githubusercontent.com/2845433/139498668-080de71f-a8c4-48b1-89be-ce8b88e2d020.png)

This is in macOS Big Sur and happens no matter whether the system theme is light or dark.

**Comment by harmtemolder** [comment]
You're right, that happens on Linux as well. Let me dive in

**Comment by harmtemolder** [comment]
Turns out we can color the window title with CSS. So now the title matches the rest of the theme
