### ISSUE TITLE
Search highlight barely visible when in preview mode

### ISSUE THREAD

**Issue by matejdro** [Slowbad/obsidian-solarized#19]
When using this theme, search results highlight while in preview mode has very low contrast with the background:

![image](https://user-images.githubusercontent.com/507922/145712308-f4906d25-e927-49b3-b846-0daeba86d769.png)

**Comment by harmtemolder** [comment]
That is strange, because for me search results are highlighted the same way as on desktop:

![Screenshot_20211213-143902_Obsidian](https://user-images.githubusercontent.com/8167752/145823028-9d28b18f-e9f7-4928-b0be-043400f4e5ca.png)

Could you switch to another theme and back to Solarized, to see if that helps?

**Comment by harmtemolder** [comment]
Ah, wait, sorry about that, I now realize you're in preview mode. Yes, there I see the same thing

**Comment by harmtemolder** [comment]
I don't think I've ever used this in-page search in preview mode, because I now see that it's the same on desktop

**Comment by matejdro** [comment]
Sorry, you are correct. I did not even notice this on the desktop. Updated the ticket title and description.

**Comment by harmtemolder** [comment]
I think I fixed it. Can you test by downloading [this version of obsidian.css](https://raw.githubusercontent.com/Slowbad/obsidian-solarized/dev/obsidian.css) to `.obsidian/themes` in your Vault folder and rename it to `Solarized.css`? (Overwrite the `Solarized.css` that's already there.)

**Comment by matejdro** [comment]
Can confirm, this fixes it on both desktop and mobile. Thanks!

**Comment by harmtemolder** [comment]
Perfect, thanks for testing
