### ISSUE TITLE
Selection not visible in code blocks

### ISSUE THREAD

**Issue by icholy** [Slowbad/obsidian-solarized#22]
The selected text color is the same as the code block background color:

![selected](https://user-images.githubusercontent.com/943597/154735072-7e4bfdb5-51bc-41c0-9601-ce5d2bf54aa4.png)

This makes it very difficult to select text in a code block because there's no visual feedback.

**Comment by harmtemolder** [comment]
I thought I had fixed this in the release of November 12th. @icholy Could you update your theme (Options > Appearance > Themes > Manage), just to make sure that you're on the newest version?

**Comment by icholy** [comment]
I updated and am still experiencing this issue.

**Comment by harmtemolder** [comment]
Could you

1. activate the default theme,
2. close Obsidian,
3. delete `.obsidian/themes/Solarized.css` in your Vault,
4. restart Obsidian,
5. select Solarized again?

**Comment by icholy** [comment]
I did that and I even tried directly copying the css from the repo into `.obsidian/themes/Solarized.css`. The selection color and block color are still the same for me.

**Comment by icholy** [comment]
FWIW, I worked around this issue by adding 

``` css
:root {
    /* ... */
    --base4: #e6dfca;
}

.theme-light {
    /* ... */
    --text-selection: var(--base4);
}
```

So that selected text is a different color than code blocks.

**Comment by harmtemolder** [comment]
That's so weird. Is this in legacy editor, live preview or reading mode? And does that code block have a syntax applied? So

    ```json

instead of

    ```

?

**Comment by harmtemolder** [comment]
This is what a selection in reading mode should look like:

![image](https://user-images.githubusercontent.com/8167752/161216120-181dea8d-48bc-4787-8b64-ff4fbaabd7d6.png)

(Without syntax highlighting)

**Comment by icholy** [comment]
Ah, that's it. It only happens in live preview mode.

**Comment by matejdro** [comment]
Can confirm, it also happens to me, but only in edit mode. I have seemingly the latest version (there does no appear to be a way to check, but I updated via obsidian theme settings and then restarted the editor with no changes).

**Comment by harmtemolder** [comment]
I've enabled live editor in my Obsidian to test this and can confirm what you were seeing. I've added a selector specifically for selections in live editor mode. Could you check if it works now?

**Comment by icholy** [comment]
@harmtemolder that fixed it. Thanks!

**Comment by harmtemolder** [comment]
@icholy Thanks for confirming (and for reporting the issue in the first place)
