### ISSUE TITLE
Tabs are rendered invisible in version 1.0.0 on Windows 10

### ISSUE THREAD

**Issue by torsteinnh** [Slowbad/obsidian-solarized#25]
After upgrading to obsidian version 1.0.0, the tabs are rendered invisible using Solarized light. No update was found for the theme, and no other entry was found in the database of available themes.
The following screenshots were taken with safe mode enabled (no community plugins) on a Windows 10 Enterprise computer with a standard 64 bit x86 processor.
<img width="744" alt="default" src="https://user-images.githubusercontent.com/38429890/196616547-a7abd099-2077-4117-854b-5e572fd6ebc8.PNG">
<img width="742" alt="solarized" src="https://user-images.githubusercontent.com/38429890/196616551-3bea7ebc-4392-4312-8a85-938388e20df5.PNG">

**Comment by DerProfessor** [comment]
The same happened to me too but with the dark version of the solarized theme. Also the theme is now listed with a `(legacy)` tag behind the theme's name. Maybe some incompatibilities with Obsidian 1.0? Perhaps an update is need to be compatible.

**Comment by harmtemolder** [comment]
Should be fixed with the new release. Could you test, please?

**Comment by torsteinnh** [comment]
The issue has been fixed, thanks :)
