### ISSUE TITLE
Not available in theme browser

### ISSUE THREAD

**Issue by erikw** [Slowbad/obsidian-solarized#26]
In the README it says that this theme can be found from the community themes manager. However I can not find it. Maybe the theme is not compatible with Obsidian 1.0?

![Screen Shot 2022-10-22 at 21 45 28](https://user-images.githubusercontent.com/175286/197359615-1bad857f-3a72-40b9-939f-4d14525989a7.png)

**Comment by muya** [comment]
@erikw It seems that this is the case.

A workaround I found to get Solarized theme was:

- Install the Minimal Theme - https://github.com/kepano/obsidian-minimal
- Install the Obsidian Minimal Settings companion plugin - https://github.com/kepano/obsidian-minimal-settings
- Update the settings in Minimal Settings to "Solarized"

![screenshot-20221028_051141](https://user-images.githubusercontent.com/1861055/198508073-c8c4c259-9495-4f78-870f-00ebc1c7cba3.png)


- Finally, tweaking the accent colour for Obsidian (under Settings > Appearance > Accent color)

It's not the same, but it's pretty close (and seems quite customizable as well)

**Comment by torsteinnh** [comment]
I think both this issue and #25 are connected to changes in obsidian 1.0, the theme is marked as legacy in my installations carried over from 0.15.
I think both issues will be fixed with a rewrite to the new standards, but I am unfortunately very inexperienced with CSS myself.

**Comment by harmtemolder** [comment]
Should be fixed with the new release. Could you test, please?

**Comment by harmtemolder** [comment]
OK, never mind, awaiting a pull request on the main Obsidian repository: https://github.com/obsidianmd/obsidian-releases/pull/1360

Once that is through, you should be able to enable Solarized again

**Comment by harmtemolder** [comment]
@erikw @muya @torsteinnh The transfer of this repository and the pull request have been applied, so you should be able to download the Solarized theme from within the theme browser again. I tested on my phone, and I see it there. Do let me know if you still don't see it
