### ISSUE TITLE
Ordered List Styling

### ISSUE THREAD

**Issue by AJKock** [Slowbad/obsidian-solarized#30]
The current ordered list styling is just 1, 1, 1
I was hoping to give some variation on level 2, 3, etc. (e.g. lower roman or lowercase)
Would it be possible to add or add as additional CSS via the Obsidian interface?

**Comment by harmtemolder** [comment]
Although I do like additional options like these, I feel that it might not be to everyone's liking. It might be better to develop this in a separate plugin? Or maybe even a CSS snippet that adds this functionality, independent of what theme is used?

**Comment by AJKock** [comment]
I would have been happy witth just one variation that shows the sub items with letters, because 
1. 
  1.
makes it very difficult to scan for sections and I've tried stylesheet include, but it didn't want to overwrite your theme's options. I wasn't sure if my code reference was wrong to the exact label you have defined in your style guide.

**Comment by harmtemolder** [comment]
I don't believe I've added anything to the theme that defines the sub items. This is probably default Obsidian behavior. Looking at the CSS it's actually quite difficult in Obsidian's HTML to identify which list items are level 1, which level 2, and which even deeper. What was your code reference? I'm happy to think along

**Comment by AJKock** [comment]
This plugin provides a way to make different lists (https://github.com/erykwalder/obsidian-list-style), but it creates lists with the first item now needing an "indicator for which type of list" to be added, which just triggers my OCD brain while in Edit mode, but looks fine in "Live" mode. In his main.ts file you can see what he calls from the Obsidian code. Maybe that can help?

**Comment by harmtemolder** [comment]
That does help, but only for reading view. I don't think there is a way (or at least no easy way) to change list styles in source or live preview modes

**Comment by harmtemolder** [comment]
So in reading view numbered lists are actual HTML `<ol>` elements. You can write CSS selectors for an `<ol>` within an `<ol>` and change its style. That would solve your issue, at least in reading view

**Comment by AJKock** [comment]
I found this solution in the forums and someone mentioned this as a possible solution [Customised Ordered Lists with CSS](https://forum.obsidian.md/t/how-to-customize-ordered-list-using-css/8242), but it has that similar problem with "Edit" mode. Then someone linked towards this [CSS Tricks for Lists](https://css-tricks.com/list-style-recipes/) and I was wondering if maybe the "colored circles variation" at the bottom, might be a nice compromise. It still uses numbers, but it gives the sub list a different background colour. What do you think?

**Comment by harmtemolder** [comment]
If you copy and paste the CSS from that first list to a file called `lists.css` in your `Vault/.obsidian/snippets/` folder, that would work for preview mode.

Regarding edit mode: those CSS tricks won't work either, because in the Electron HTML the ordered lists are not actually ordered lists, but just regular `<span>`s.
