### ISSUE TITLE
Hard to read mermaid

### ISSUE THREAD

**Issue by cannibutthenottakenone** [Slowbad/obsidian-solarized#41]
Mermaid mindmaps are very hard to read, following is an example image
![image](https://github.com/user-attachments/assets/41655976-01f2-4e28-acb5-4edff306d472)
Could you tweak the colors? Or tell me how to do it without changing the rest of the theme?

**Comment by harmtemolder** [comment]
I edited the text color and tried with the example on <https://mermaid.js.org/syntax/mindmap.html>, and a couple of other types of graphs. Should be fixed:

![Screenshot_2024-12-10_13-12-47](https://github.com/user-attachments/assets/f8e948b9-b67a-4676-a692-7c7a10e7ee9e)
