### ISSUE TITLE
No distinction between existing, non-existing notes  and regular text in Live Preview and Reading View

### ISSUE THREAD

**Issue by gkoller** [Slowbad/obsidian-solarized#42]
Default Obsidian theme makes a clear distinction between existing notes, non-existing notes and regular text in  _Live Preview_ and _Reading View_. The Obsidian Solarized theme does not. 

| Theme | Mode | Example | Problem |
| --- | --- | --- | --- |
| Default | Live Preview | <img width="315" alt="default_theme_live_preview_existing_versus_non_existing" src="https://github.com/user-attachments/assets/d94ce617-ee66-4720-b22c-66869ca242cc" /> | None |
| Solarized | Live Preview | <img width="320" alt="solarized_existing_versus_live_preview_non_exist  ing" src="https://github.com/user-attachments/assets/de3aae21-0469-43f1-9f4e-ef97dd60402d" />  | Non-existing note link suggests the link is to a an existing note |
| Default | Reading View | <img width="322" alt="default_theme_reading_view_existing_versus_non_existing" src="https://github.com/user-attachments/assets/606d9267-8082-4e48-9603-cfbeb5f4b2ac" /> | None |
| Solarized | Reading View | <img width="328" alt="solarized_existing_versus_reading_view_non_exist  ing" src="https://github.com/user-attachments/assets/014714af-45c1-4b95-b5df-712c3b7bb6fb" /> | Non-existing node is rendered as regular text; no suggestion it can be clicked on at all (unless one hovers over it)

**Comment by harmtemolder** [comment]
Sorry, that crept in there when refactoring the underlying code. Should be fixed now

**Comment by gkoller** [comment]
> Sorry, that crept in there when refactoring the underlying code. Should be fixed now

Thank you for the fix and thank you for providing this theme at all. It's really nice to be able to use Obsidian with my favorite color scheme.
