### ISSUE TITLE
Selection issue

### ISSUE THREAD

**Issue by derwok** [Slowbad/obsidian-solarized#8]
In Edit mode selections for some styles gets BEHIND some other formatting:
![image](https://user-images.githubusercontent.com/4393698/83349058-1852e700-a332-11ea-8548-8e479343aad5.png)

Especially inline code looks weird:
![image](https://user-images.githubusercontent.com/4393698/83349110-7f709b80-a332-11ea-88b7-3de154b18e9c.png)

I don't really get where this comes from? Eventually some `!import` overlapping?
Could you fix this?

PS.
In Preview Mode it looks good
![image](https://user-images.githubusercontent.com/4393698/83349123-a4650e80-a332-11ea-8a21-27bcee26f5eb.png)

**Comment by Slowbad** [comment]
As far as I'm aware this isn't fixable without changing how the html is generated by CodeMirror for inline code. When you select something in the editor view it generates something like this to represent a selection.

```html
<div style="position: relative; z-index: 1;">
  <div class="CodeMirror-selected" style="position: absolute; left: 4px; top: 77px; width: 1068px; height: 29px;"></div>
  <div class="CodeMirror-selected" style="position: absolute; left: 4px; top: 134px; width: 150.406px; height: 29px;"></div>
  <div class="CodeMirror-selected" style="position: absolute; left: 4px; top: 106px; width: 1068px; height: 28px;"></div>
</div>
```

CodeMirror would have to generate a separate element for the background color of the inline code to get this to work with how they currently implement selection.
