### ISSUE TITLE
Confirm Delete unreadable

### ISSUE THREAD

**Issue by OogieM** [Slowbad/obsidian-solarized#9]
The text in the red Confirm Delete boxes is unreadable. Or at least I can't read it. 
![Screen Shot 2020-09-14 at 3 43 21 PM](https://user-images.githubusercontent.com/2394446/93141868-2d197780-f6a2-11ea-8f8b-b46520c109a3.png)

Is there any way to make the font bigger or somethng that stands out more? Not sure if it's a theme issue or an Obsidian Issue. It is sort of  readable in the default light theme.

**Comment by Slowbad** [comment]
It's a theme issue. I can take a look tonight and come up with something that has more contrast for readability. I can read it but it strains my eyes to do so.
